<?php
/**
 * @file
 * Lazy Load module improves image loading performance by delaying the loading
 * of images outside the viewport and by temporarily showing lightweight
 * versions of large images while they are being fetched.
 */

/**
 * Implements hook_config_info().
 */
function lazyload_config_info() {
  return array(
    'lazyload.settings' => array(
      'label' => t('Lazy Load settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function lazyload_menu() {
  return array(
    'admin/config/media/lazyload' => array(
      'title' => 'Lazy Load',
      'description' => 'Configure Lazy Load.',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('lazyload_admin_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'lazyload.admin.inc',
    ),
  );
}

/**
 * Implements hook_library_info().
 */
function lazyload_library_info() {
  $libraries['lazyload'] = array(
    'title' => 'Lazy Load',
    'website' => 'https://github.com/verlok/vanilla-lazyload',
    'version' => '19.1.3',
    'js' => array(
      backdrop_get_path('module', 'lazyload') . '/library/lazyload.min.js' => array(
        'group' => JS_LIBRARY,
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_init().
 */
function lazyload_init() {
  $config = config('lazyload.settings');

  // Nothing to do if the js plugin is disabled.
  if (!empty($config->get('disable_js_plugin'))) {
    return;
  }

  // Nothing to do if page is blacklisted.
  if (!lazyload_is_allowed()) return;

  // Get the module's directory.
  $module_dir = backdrop_get_path('module', 'lazyload');

  // Add library, settings and script that initiates Lazy Load js.
  backdrop_add_library('lazyload', 'lazyload', TRUE);
  $js_settings['lazyload'] = array(
    'threshold' => $config->get('lazy_threshold'),
  );
  backdrop_add_js($js_settings, 'setting');
  backdrop_add_js($module_dir . '/js/lazyload.js', array('scope' => 'footer', 'weight' => 999));
}

/**
 * Changes <img> tag in text fields so they could be lazy loaded.
 */
function lazyload_preprocess_field(&$variables, $hook) {
  // Check if inline image tag processing is enabled.
  if (!config_get('lazyload.settings', 'enable_inline')) {
    return;
  }
  // Check if filed type is defined.
  if (empty($variables['element']['#field_type'])) {
    return;
  }
  // Check if the field type is one of the text kinds.
  switch ($variables['element']['#field_type']) {
    case 'text':
    case 'text_long':
    case 'text_with_summary':
      // Move on to the rest of the code if field is a text.
      break;
    default:
      // Return in other cases.
      return;
  }
  // Use regex to find <img> tag and capture 'src' value.
  $pattern = '#<img\b[^>]*\ssrc\s*=\s*["\'](.*?)["\'][^>]*>#';
  foreach ($variables['items'] as &$item) {
    if (!empty($item['#markup'])) {
      // Replace <img> tag src if found.
      $item['#markup'] = preg_replace_callback($pattern, 'lazyload_img_tag_replace', $item['#markup'], -1, $cnt);
    }
  }
}

/**
 * Replaces <img> tag 'src' value to the preview image URL and applies original
 * 'src' to 'data-lazyload-src'. This function is used as a callback for
 * preg_callback_replace() with regular expression that captures 'src' value.
 */
function lazyload_img_tag_replace($matches) {
  $img_tag = $matches[0];
  $img_src = $matches[1];
  $preview_src = lazyload_get_preview_url($img_src);
  if ($preview_src !== FALSE) {
    $img_tag = str_replace('src="' . $img_src . '"', 'src="' . $preview_src . '"', $img_tag);
    $img_tag = rtrim($img_tag, '>') . ' data-lazyload-src="' . $img_src . '">';
  }
  return $img_tag;
}

/**
 * Implements template_preprocess_image()
 *
 * Makes src attribute point to a preview or blank image and assigns the actual
 * image URL to the data-src attribute so that lazyload js plugin could process
 * the image. Only images that are above file size threshold are processed.
 */
function lazyload_preprocess_image(&$variables) {
  // Nothing to do if page is blacklisted.
  if (!lazyload_is_allowed()) return;

  // Get either path or URI from the variables.
  $path_or_uri = $variables['uri'] ? $variables['uri'] : $variables['path'];

  // Try to get preview image URL.
  $img_preview_url = lazyload_get_preview_url($path_or_uri);
  if ($img_preview_url !== FALSE) {
    // Assign preiew image to src attribute and main image to lazyload-src.
    // Lazyload js plugin will assign main image to src once loading is complete.
    $variables['attributes']['src'] = $img_preview_url;
    $variables['attributes']['data-lazyload-src'] = file_create_url($path_or_uri);
    $variables['attributes']['class'][] = 'lazyload-item';
  }
}

/**
 * Returns URL of the preview image derived from the main image.
 * Checks file size limit and generates preview style image if needed.
 * Contains important logic that prepares <img> tag for lazy loading.
 */
function lazyload_get_preview_url($img_uri) {
  $img_path = ''; // Path to image in the src of the <img> tag.
  $img_orig_path = ''; // Path to original image (without style applied).
  $img_preview_path = ''; // Path to the preview image style.

  // Make sure there is no slash at the beginning of the URI.
  $img_uri = ltrim($img_uri,  "\n\r\t\v\x00/\\");

  // Get path to public file storage.
  $public_path = config_get('system.core', 'file_public_path');

  // Potentially there could be various types of URI as an input, so convert
  // it to either {scheme}://{local path} or just {local path} format so that
  // image_style_path() and image_style_url() could correctly process them.
  $scheme = file_uri_scheme($img_uri);
  switch ($scheme) {
    case 'http':    // Full URL.
    case 'https':
      // Get local path from the URI and trim the slash at the beginning.
      $img_path = parse_url($img_uri, PHP_URL_PATH);
      $img_path = ltrim($img_path, '/\\');
      // If starts with public path then replace it with 'public' scheme.
      // That way it will be correctly processed by image_style_path() and
      // image_style_url() functions.
      if (str_starts_with($img_path, $public_path)) {
        $img_path = substr($img_path, strlen($public_path) + 1);
        $img_path = 'public://' . $img_path;
      }
      break;
    case '':    // URI without a scheme.
      // Check if file starts with public path and replace it with public scheme.
      if (str_starts_with($img_uri, $public_path)) {
        $img_path = 'public://' . substr($img_uri, strlen($public_path) + 1); // +1 to remove slash.
      }
      else {
        // Keep files from outside the 'public' scheme as is. In many cases
        // it is still possible to make preview work for them.
        $img_path = $img_uri;
      }
      break;
    default:    // URI with a scheme.
      $img_path = $img_uri;    // Take URI as is.
      break;
  }

  // Try to get image file size.
  // Here ALL ERRORS ARE SUPPRESSED to avoid warnings when file does not exist.
  // If something does not work right then the '@' must be removed for debugging!
  $file_size = @filesize($img_path);
  // Skip the file if it's size can not be read or zero.
  if ($file_size == FALSE) {
    return FALSE;
  }

  // From this point the module's settings are needed.
  $config = config('lazyload.settings');

  // Check if file size is above the size threshold.
  $min_file_size = $config->get('img_min_file_size');
  if ($file_size < $min_file_size) {
    return FALSE;
  }

  // By default set the preview URL to be a blank 1x1 pix image.
  $img_preview_url = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==';

  // Check if lazy load is set to use the preview image.
  if ($config->get('loading_vis') === 'preview') {
    // Get preview style name.
    $preview_style_name = $config->get('preview_style');
    if (!empty($preview_style_name)) {
      // Check if the image path points at the original image or the one with a
      // style applied. In case there is a need to create a derivative image,
      // that image should be based on the original.
      $pattern = '#^public://styles/([^/]+)/([^/]+)/(.*)$#';
      if (preg_match($pattern, $img_path, $matches)) {
        // $matches[1] — style name of the image.
        // $matches[2] — scheme.
        // $matches[3] — path to file without style and scheme directories.
        $img_orig_path = "public://{$matches[3]}";
        $img_preview_path = "public://styles/{$preview_style_name}/{$matches[2]}/{$matches[3]}";
      }
      else {
        // Image path points to original so get the preview image path as usual.
        $img_orig_path = $img_path;
        $img_preview_path = image_style_path($preview_style_name, $img_orig_path);
      }
      // Check that preview image file exists and get it's URL.
      if (_image_source_image_exists($img_preview_path)) {
        $img_preview_url = image_style_url($preview_style_name, $img_orig_path);
      }
      else {
        // If preview image doesn't exist try to generate it.
        $preview_style = image_style_load($preview_style_name); // Get the style data.
        // The style could be deleted so check that we have it.
        if (!empty($preview_style)) {
          // Try to create an image in the 'preview' style.
          $preview_img_created = image_style_create_derivative($preview_style, $img_orig_path, $img_preview_path);
          // If succeeded get the preview image URL.
          if ($preview_img_created) {
            $img_preview_url = image_style_url($preview_style_name, $img_orig_path);
          }
        }
      }
    }
  }
  return $img_preview_url;
}

/**
 *  Checks if Lazy Load is allowed to run on current page.
 */
function lazyload_is_allowed() {
  // Keep result in a static variable so that check is performed only once per
  // page request while the result is accessible via subsequent function calls.
  static $is_allowed = NULL;
  if (isset($is_allowed)) {
    return $is_allowed;
  }

  $current_path = backdrop_get_path_alias();
  $config = config('lazyload.settings');

  // Apply administrative pages filter if enabled.
  if (!empty($config->get('pages_no_admin'))) {
    if (path_is_admin($current_path)) {
      $is_allowed = FALSE;
      return $is_allowed;
    }
  }

  // Start applying page filter and the filter rule.
  $path_patterns = $config->get('pages_paths');
  $rule  = $config->get('pages_filter_rule');
  // Check if current page matches any of the path patterns.
  $match = backdrop_match_path($current_path, $path_patterns);
  // Check the match against the 'Filter rule'.
  switch ($rule) {
    case 'exclude':
      $is_allowed = $match ? FALSE : TRUE;
      break;
    case 'include':
      $is_allowed = $match ? TRUE : FALSE;
  }
  return $is_allowed;
}

