<?php
/**
 * @file
 * Lazy Load module improves image loading performance by delaying the loading
 * of images outside the viewport and by temporarily showing lightweight
 * versions of large images while they are being fetched.
 */

/**
 * Implements hook_config_info().
 */
function lazyload_config_info() {
  return array(
    'lazyload.settings' => array(
      'label' => t('Lazy Load settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function lazyload_menu() {
  return array(
    'admin/config/media/lazyload' => array(
      'title' => 'Lazy Load',
      'description' => 'Configure Lazy Load.',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('lazyload_admin_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'lazyload.admin.inc',
    ),
  );
}

/**
 * Implements hook_library_info().
 */
function lazyload_library_info() {
  $libraries['lazyload'] = array(
    'title' => 'Lazy Load',
    'website' => 'https://github.com/verlok/vanilla-lazyload',
    'version' => '19.1.3',
    'js' => array(
      backdrop_get_path('module', 'lazyload') . '/library/lazyload.min.js' => array(
        'group' => JS_LIBRARY,
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_init().
 */
function lazyload_init() {
  $config = config('lazyload.settings');

  // Nothing to do if the js plugin is disabled.
  if (!empty($config->get('disable_js_plugin'))) {
    return;
  }

  // Nothing to do if page is blacklisted.
  if (!lazyload_is_allowed()) return;

  // Get module's directory.
  $module_dir = backdrop_get_path('module', 'lazyload');

  backdrop_add_library('lazyload', 'lazyload', TRUE);

  $js_settings['lazyload'] = array(
    'threshold' => $config->get('lazy_threshold'),
  );
  backdrop_add_js($js_settings, 'setting');
  backdrop_add_js($module_dir . '/js/lazyload.js', array('scope' => 'footer', 'weight' => 999));
}

/**
 * Implements template_preprocess_image()
 *
 * Makes src attribute point to a preview or blank image and assigns the actual
 * image url to the data-src attribute so that lazyload js plugin could process
 * the image. Only images that are above pixel count threshold are processed.
 *
 * Why pixel count is used for the threshold and not image filesize?
 * - Width, height are almost always available in $variables unlike filesize.
 * - Multiplication width*height is faster than checking file size (and file
 *   existence) directly when filesize is not present in variables.
 * - From user point of view it is easier to refer to 'image size'/'image style'
 *   than to file size. When you know the size of a preview style, it is easy
 *   to understand what should be the threshold and vise versa.
 * - It is a rare case when one need to triage files with different file
 *   compression types like jpg along with bmp. Most websites tend to use
 *   formats with strong compression like jpg, webp, png.
 */
function lazyload_preprocess_image(&$variables) {
  // Nothing to do if page is blacklisted.
  if (!lazyload_is_allowed()) return;

  $config = config('lazyload.settings');

  // Get either path or uri from the variables.
  $path_or_uri = $variables['uri'] ? $variables['uri'] : $variables['path'];

  // Get image pixel count as width x height multiplication.
  if (isset($variables['width']) && isset($variables['height'])) {
    $img_pixel_count = $variables['width'] * $variables['height'];
  }
  else {
    // Ignore the image if we can't get width or height.
    return;
  }

  // Ignore image if it is below the pixel count threshold.
  if ($img_pixel_count < $config->get('img_min_pix_count')) {
    return;
  }

  // By default set blank transparent 1x1 px image as the preview.
  $preview_img = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==';

  // If defined in config, get style url of the preview image.
  if ($config->get('loading_vis') === 'preview') {
    $preview_style_name = $config->get('preview_style');
    if (!empty($preview_style_name)) {
      // Get image filename.
      $img_file_name = backdrop_basename($path_or_uri);
      // Get path to the preview image style.
      $preview_path = image_style_path($preview_style_name, $img_file_name);
      // Check that file exists and use its url as preview image source.
      if (_image_source_image_exists($preview_path)) {
        $preview_img = image_style_url($preview_style_name, $img_file_name);
      }
      else {
        // If preview image doesn't exist try to generate it.
        $preview_style = image_style_load($preview_style_name); // Get the style data.
        $preview_img_created = image_style_create_derivative($preview_style, $path_or_uri, $preview_path);
        // If succeeded assign the image url as preview image source.
        if ($preview_img_created) {
          $preview_img = image_style_url($preview_style_name, $img_file_name);
        }
      }
    }
  }
  // Assign preiew image to src attribute and main image to lazyload-src.
  // Lazyload js plugin will assign main image to src one it is done loading.
  $variables['attributes']['src'] = $preview_img;
  $variables['attributes']['data-lazyload-src'] = file_create_url($path_or_uri);
  $variables['attributes']['class'][] = 'lazyload-item';
}

/**
 *  Checks if Lazy Load is allowed to run on current page.
 */
function lazyload_is_allowed() {
  // Keep result in a static variable so that check is run only once per page
  // request while the result is accessible via subsequent function calls.
  static $is_allowed = NULL;
  if (isset($is_allowed)) {
    return $is_allowed;
  }

  $config = config('lazyload.settings');
  $current_path = backdrop_get_path_alias();

  // Apply administrative pages filter if enabled.
  if (!empty($config->get('pages_no_admin'))) {
    if (path_is_admin($current_path)) {
      $is_allowed = FALSE;
      return $is_allowed;
    }
  }

  // Start applying page filter and the filter rule.
  $path_patterns = $config->get('pages_paths');
  $rule  = $config->get('pages_filter_rule');
  // Check if current page matches any of the path patterns.
  $match = backdrop_match_path($current_path, $path_patterns);
  // Check the match against the 'Filter rule'.
  switch ($rule) {
    case 'exclude':
      $is_allowed = $match ? FALSE : TRUE;
      break;
    case 'include':
      $is_allowed = $match ? TRUE : FALSE;
  }
  return $is_allowed;
}

